name: zerocart
version: 1.0.0+4
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  pin_code_fields: ^8.0.1
  step_progress_indicator: ^1.0.2
  dotted_line: ^3.1.0
  #remomve light_carousel from HomeView add carousel_slider
  light_carousel: ^0.0.4
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.2.0
  http: ^0.13.5
  connectivity_plus: ^4.0.1
  flutter_html: ^3.0.0-beta.2
  intl: ^0.18.0
  easy_image_viewer: ^1.2.0
  dio: ^5.2.0+1
  carousel_slider: ^4.2.1
  razorpay_flutter: ^1.3.5
  timer_count_down: 2.2.2
  multiple_search_selection: ^2.5.2
  multi_select_flutter: ^4.1.3
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_launcher_icons:
  get: 4.6.5
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter_local_notifications: ^15.1.1
  permission_handler: ^10.4.3
  open_apps_settings: ^0.0.4
  firebase_messaging: ^14.6.7
  image_cropper: ^3.0.0
  google_sign_in: 5.3.0
  firebase_auth: ^4.1.2
  location: ^4.2.0
  geocoder2: ^1.4.0
  location_geocoder: ^1.0.5
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  chewie_audio: ^1.5.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo_icon_foreground.png"


flutter: 
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700