// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-9rMBhZ7XlEZYUGh6VkwbCuVCxZUYMf4',
    appId: '1:777331500532:android:cf724008257821feab45a1',
    messagingSenderId: '777331500532',
    projectId: 'zerocart-aca66',
    databaseURL: 'https://zerocart-aca66-default-rtdb.firebaseio.com',
    storageBucket: 'zerocart-aca66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeoz-a1W7Bqyvc3RW28trE4lt8wT13CdA',
    appId: '1:777331500532:ios:05c3a3390d180c56ab45a1',
    messagingSenderId: '777331500532',
    projectId: 'zerocart-aca66',
    databaseURL: 'https://zerocart-aca66-default-rtdb.firebaseio.com',
    storageBucket: 'zerocart-aca66.appspot.com',
    iosClientId: '777331500532-btcqnldb6e4obnrjgjgkgqki40aft6qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.zerocart',
  );
}
